services:
  web:
    build: ./web
    ports:
      - "3000:3000"
    environment:
      - VOICE_API_URL=http://engine:5000
    depends_on:
      - engine
      - redis
    restart: unless-stopped

  engine:
    build: ./engine
    ports:
      - "5000:5000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]  # persistent data with AOF

  worker:
    build: ./worker
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    restart: unless-stopped
